### ISSUE TITLE
only works if both deb AND rpm files exist

### ISSUE THREAD

**Issue by tstack** [golift/upload-packagecloud#2]
The `for` loops for the deb/rpm files will enter the body with the pattern as the value if no files match the pattern:

https://github.com/golift/upload-packagecloud/blob/baff4a65b2989554518729b6d0bcf6f14bbf12ce/upload.sh#L40

Can you add `shopt -s nullglob` so that the loops do nothing if there is no matching file.

**Comment by davidnewhall** [comment]
That seems reasonable.
